version: "3.7"

services:

  prisma:
    restart: always

  mysql:
    restart: always

  pma:
    restart: always

  front:
    restart: always
    environment: 
      ENV_MODE: production
    command: yarn start-ssr

  api:
    restart: always
    environment: 
      - endpoint=${prod_endpoint}
    command: "yarn start-server"

  proxy:
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
